#FRANCISCO JAVIER PEREZ MARTINEZ  DNI: 74384305M

OPTS = -Wall -O3 -std=c++11

maxsum-greedy: maxsum-greedy.cc
	g++ ${OPTS} -o maxsum-greedy maxsum-greedy.cc

tar: maxsum-greedy.cc makefile
	tar cvfz 74384305M.tar.gz maxsum-greedy.cc makefile
