#FRANCISCO JAVIER PEREZ MARTINEZ  DNI: 74384305M

OPTS = -Wall -O3 -std=c++11

maxsum-bt: maxsum-bt.cc
	g++ ${OPTS} -o maxsum-bt maxsum-bt.cc

tar: maxsum-bt.cc makefile
	tar cvfz 74384305M.tar.gz maxsum-bt.cc makefile
