#FRANCISCO JAVIER PEREZ MARTINEZ  DNI: 74384305M

OPTS = -Wall -O3 -std=c++0x

maxsum: maxsum.cc
	g++ ${OPTS} -o maxsum maxsum.cc

tar: maxsum.cc makefile
	tar cvfz 74384305M.tar.gz maxsum.cc makefile
